name: divine_stream
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  get_it: ^7.6.7
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.0.1
  flutter_background_service: ^5.0.4
  intl: ^0.18.1
  firebase_core: ^3.13.0
  fluttertoast: ^8.2.5
  rxdart: ^0.28.0
  flutter_dotenv: ^6.0.0
  flutter_swipe_action_cell: ^3.1.6
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.4.0
  connectivity_plus: ^5.0.0
  http: ^1.2.1
  cloud_firestore: ^5.5.0


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/app_icon.png"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
